language: haskell

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"

ghc:
- 8.8.1
- 8.6.5
- 8.4.4
- 8.2.2
- 8.0.2
- 7.10.3
- 7.8.4
- 7.6.3

install:
- cabal install --only-dependencies
- cabal build

script:
- echo 'No tests'
